const products = [
  {
    '_id': '1',
    'name': 'Blossom Bomb',
    'image': '/images/oneperfume.jpg',
    'description':
      'This floral perfume for women explodes with an intoxicating whirl of blossoms. The warm scent of patchouli and vanilla grounds the fresh fragrance, adding a sensual twist on the scent reminiscent of a room filled with rose petals.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'rose, patchouli, vanilla',
    'size': '100 ml',
    'price': 795.00,
    'countInStock': 70,
    'rating': 4.6,
    'numReviews': 12,
  },
  {
    '_id': '2',
    'name': 'Free Spirit',
    'image': '/images/twoperfume.jpg',
    'description':
      'A bold and floral womens fragrance. A statement feminine scent for those who live by their own rules. Lavender essence from France combines with the sensuality of Moroccan orange blossom and a daring note of vanilla extract for a unique long-lasting scent.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'lavendar, orange blossom, musk',
    'size': '100 ml',
    'price': 845.00,
    'countInStock': 55,
    'rating': 4.7,
    'numReviews': 16,
  },
  {
    '_id': '3',
    'name': 'Victorian Beauty',
    'image': '/images/threeperfume.jpg',
    'description':
      'The intense mineral character of oakmoss is enveloped in the voluptuous softness of mirabelle plum. From this freshness emanates a bright floral note carried by freesia. Natural ingredients brought into focus by the perfumer Quentin Bisch, revealing accords as exhilarating as the feeling of escape they inspire.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'oakmoss, freesia, mirabelle liquor',
    'size': '50 ml',
    'price': 695.00,
    'countInStock': 0,
    'rating': 4.8,
    'numReviews': 11,
  },
  {
    '_id': '4',
    'name': 'Her Power',
    'image': '/images/fourperfume.jpg',
    'description':
      'This floral-fruity fragrance is combined with thick gourmand shades making it an equivalent of the modern perfume scene. Gourmand trendy composition touched many designer collections suggesting that the focus lies on sophisticated sweetness.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'peach, osmanthus, cacao',
    'size': '50 ml',
    'price': 595.00,
    'countInStock': 51,
    'rating': 4.4,
    'numReviews': 12,
  },
  {
    '_id': '5',
    'name': 'Meadow Goddess',
    'image': '/images/fiveperfume.jpg',
    'description':
      'A lively floral scent, enhanced by rose and violet and topped with juicy blackcurrants. Borrowed from the succulent cereal fields, where grains and flowers mingle, our poppies are cocooned by bran and cotton-soft barley.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'black currant, poppy, barley',
    'size': '50 ml',
    'price': 695.00,
    'countInStock': 47,
    'rating': 4.9,
    'numReviews': 10,
  },
  {
    '_id': '6',
    'name': 'Hepburn Grace',
    'image': '/images/sixperfume.jpg',
    'description':
      'Embrace your beauty and express your femininity. Amazingly clean, and beautifully feminine scent features notes of welcoming bergamot to greet the senses, irresistibly soft, clean muguet blossoms, and lasting musk with its classic beauty.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'bergamot, jasmine, musk',
    'size': '50 ml',
    'price': 595.00,
    'countInStock': 30,
    'rating': 4.9,
    'numReviews': 12,
  },
  {
    '_id': '7',
    'name': 'Miss Paris',
    'image': '/images/sevenperfume.jpg',
    'description':
      'A dazzling fragrance that represents a modern olfactory interpretation of love, free from all the obstacles, dedicated and intense.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'raspberry, peony, white musk',
    'size': '50 ml',
    'price': 695.00,
    'countInStock': 40,
    'rating': 4.4,
    'numReviews': 10,
  },
  {
    '_id': '8',
    'name': 'Fate',
    'image': '/images/eightperfume.jpg',
    'description':
      'A wave of extreme freshness meets with the flowery notes and continues with sensual spicy composition. The door open to adventure and unknown, just like lips ready for a kiss.',
    'brand': 'The Scent Studio',
    'category': 'Perfume',
    'accords': 'pink pepper, jasmine, vetiver',
    'size': '100 ml',
    'price': 895.00,
    'countInStock': 20,
    'rating': 4.7,
    'numReviews': 8,
  },

]


export default products
